"""Версия приложения и адрес обновлений."""

APP_NAME = "M9 Gate"
APP_VERSION = "1.2.5-beta"
APP_COMPANY = "Тех.ру"
APP_DEVELOPER = "Дима"
APP_DEVELOPER_URL = "https://t.me/ImaGunDi"
GITHUB_REPO = "AshcookieKing/M9_TicketSystem"
UPDATE_ASSET = "M9_Gate.zip"
UPDATE_EXE = "M9_Gate.exe"
